pagetitle="Парады ў паляпшэнні артыкулаў"
thish1="парады ў паляпшэнні артыкулаў для ${language}wiki"
subclause1name="моўныя раздзелы, з якіх капіяваць спасылкі"
subclause1="This is the list of languages to spy links from with the amount of articles suggested for further translation or wikification and with the amount of isolated articles, which could be linked."
subclause2name="languages to translate from"
subclause2="This is the list of languages to translate and spy links from with the amount of articles suggested for translation and with the amount of isolated articles, which could be linked."